name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  PACKAGE_NAME: appuio-reporting-aldebaran

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_yaml
          - lint_adoc
          - lint_commodore
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.PACKAGE_NAME }}
      - name: Compile component
        run: make test -e instance=${{ matrix.instance }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.PACKAGE_NAME }}
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
